# Common Labels
labels:
  app: "default-data-handler"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "default-data-handler"


# Container Configs
image:
  repository: "default-data-handler"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/default-data-handler/health"
  readinessProbePath: "/default-data-handler/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 512Mi
heap: "-Xmx512m -Xms512m"
java-args: "-Dspring.profiles.active=monitoring"
egov-mdms-schema-definition-save-topic: "save-mdms-schema-definition"
egov-mdms-data-save-topic: "save-mdms-data"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXT_PATH
    value: /default-data-handler
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2  
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: default-data-handler
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: JAVA_ENABLE_DEBUG
    value: "true" 
